// Build the walkable grid the server uses, from the same floor plan the 3D client
// builds its own grid from (app/public/js/data.js), so both agree on every wall.
// Writes party/02_grid.js. Party mode keeps the HoH door open.
import { writeFileSync } from "node:fs";
import { WALLS, FURNITURE, WORLD } from "../app/public/js/data.js";

const C = 0.5;
const gw = Math.ceil(WORLD.w / C), gd = Math.ceil(WORLD.d / C);
const block = new Uint8Array(gw * gd);
const mark = (x0, z0, x1, z1) => {
  for (let i = Math.floor(Math.min(x0, x1) / C); i <= Math.floor(Math.max(x0, x1) / C); i++)
    for (let j = Math.floor(Math.min(z0, z1) / C); j <= Math.floor(Math.max(z0, z1) / C); j++)
      if (i >= 0 && j >= 0 && i < gw && j < gd) block[j * gw + i] = 1;
};
for (const [x0, z0, x1, z1, , kind] of WALLS) {
  const pad = kind === "hedge" ? 0.4 : 0.25;
  mark(Math.min(x0, x1) - pad, Math.min(z0, z1) - pad, Math.max(x0, x1) + pad - 0.01, Math.max(z0, z1) + pad - 0.01);
}
mark(30, 0, 33, 5);
for (const f of FURNITURE) {
  if (!f.block) continue;
  const [x, z] = f.p;
  let [w, d] = f.s;
  if (f.r && Math.abs(Math.sin(f.r)) > 0.5) [w, d] = [d, w];
  mark(x - w / 2 + 0.05, z - d / 2 + 0.05, x + w / 2 - 0.05, z + d / 2 - 0.05);
}
const rows = [];
for (let j = 0; j < gd; j++) { let r = ""; for (let i = 0; i < gw; i++) r += block[j * gw + i] ? "#" : "."; rows.push(r); }
const out = `// ---------------------------------------------------------------------------
// The walk grid: ${gw} x ${gd} cells of ${C} m, "#" blocked. Generated by
// tools/make_grid.mjs from the client's floor plan; do not edit by hand.
// ---------------------------------------------------------------------------

const CELL = ${C}, GW = ${gw}, GD = ${gd};
const GRID = [
${rows.map((r) => `  "${r}",`).join("\n")}
].join("");
`;
writeFileSync(new URL("../party/02_grid.js", import.meta.url), out);
console.log("grid", gw, "x", gd, "blocked", block.reduce((a, b) => a + b, 0));
console.log(rows.join("\n"));
