/**
 * WAHALA HOUSE: Party Mode.
 *
 * Five to ten players share the house. One or two of them are secret
 * Saboteurs. Housemates do chores to fill the task bar; Saboteurs fake chores,
 * strike housemates who are alone with them and sabotage the house. A body or
 * the emergency bell calls a House Meeting: everyone talks, then votes someone
 * out. AI housemates fill empty seats and take over for anyone who drops.
 *
 * Contract: six pure exports, no imports, no timers, no Math.random or
 * Date.now. The room injects the server clock as `action._now` and drives time
 * with `{t:"_tick"}` system actions; randomness is a seeded generator in state.
 */

export const meta = { game: "Wahala House", minPlayers: 1, maxPlayers: 10 };

// ---------------------------------------------------------------------------
// Timings (ms) and tuning
// ---------------------------------------------------------------------------

const T = {
  intro: 6500,
  firstKill: 12000,
  sabFirst: 15000,
  sabCd: 30000,
  gas: 40000,
  bellLock: 15000,
  result: 7500,
  fill: 30000,
  fillFull: 3000,
  away: 15000,
  endBack: 25000,
  taskSlack: 0.75,
};
const SPEED = { walk: 2.6, maxHuman: 6, slack: 1.2 };
const RANGE = { strike: 1.9, report: 2.6, use: 2.3, bell: 2.3 };
const VISION = { H: 6.5, S: 7.5, nepa: 2.6, close: 3.2 };
const OPTS_DEFAULT = { fill: 8, sabs: 0, kill: 40, discuss: 40, vote: 25, reveal: true };
const OPTS_ALLOWED = { fill: [5, 6, 7, 8, 9, 10], sabs: [0, 1, 2, 3], kill: [20, 25, 30, 35, 40, 50], discuss: [20, 30, 40, 60, 90], vote: [15, 20, 25, 30, 45], reveal: [true, false] };

/** Character looks a seat can wear: the ten housemates plus the two player models. */
const LOOKS = ["tobi", "ada", "musa", "ivie", "kunle", "ebi", "nedu", "nkoyo", "zee", "mekus", "pf", "pm"];
const CAST = {
  tobi: { name: "Tobi", ex: ["Omo!", "Chai!", "Odogwu!"] },
  ada: { name: "Ada", ex: ["Ehen!", "Nne!", "Chineke!"] },
  musa: { name: "Musa", ex: ["Hmm.", "Wallahi.", "Ah."] },
  ivie: { name: "Ivie", ex: ["Ehn ehn.", "Darling!", "Oya!"] },
  kunle: { name: "Kunle", ex: ["Jesu!", "Ah ah!", "Haba!"] },
  ebi: { name: "Ebi", ex: ["Tufiakwa!", "Abeg!", "See me see trouble!"] },
  nedu: { name: "Nedu", ex: ["Interesting.", "Omo.", "See ehn."] },
  nkoyo: { name: "Nkoyo", ex: ["Eh heh!", "My God!", "Nawa o!"] },
  zee: { name: "Zee", ex: ["Excuse me?", "Wow.", "Kai!"] },
  mekus: { name: "Mekus", ex: ["Nwanne!", "Ahn ahn!", "Hear me!"] },
  pf: { name: "Housemate", ex: ["Omo!", "Ehen!"] },
  pm: { name: "Housemate", ex: ["Omo!", "Chai!"] },
};
const BOT_ORDER = ["tobi", "ada", "musa", "ivie", "kunle", "ebi", "nedu", "nkoyo", "zee", "mekus"];

// ---------------------------------------------------------------------------
// Seeded randomness (mulberry32 over a uint32 kept in state)
// ---------------------------------------------------------------------------

function rnd(s) {
  s.rng = (s.rng + 0x6d2b79f5) >>> 0;
  let t = s.rng;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
const R = {
  int: (s, n) => Math.floor(rnd(s) * n),
  pick: (s, a) => a[Math.floor(rnd(s) * a.length)],
  chance: (s, p) => rnd(s) < p,
  range: (s, a, b) => a + rnd(s) * (b - a),
  shuffle: (s, a) => { const b = a.slice(); for (let i = b.length - 1; i > 0; i--) { const j = Math.floor(rnd(s) * (i + 1)); [b[i], b[j]] = [b[j], b[i]]; } return b; },
};
function hash(str) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
  return h >>> 0;
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

const clone = (o) => JSON.parse(JSON.stringify(o));
const dist = (a, b) => Math.hypot(a.x - b.x, a.z - b.z);
const pOf = (s, id) => s.ps.find((p) => p.id === id) || null;
const playing = (s) => s.ps.filter((p) => !p.spec);
const living = (s) => s.ps.filter((p) => !p.spec && p.alive);
const humans = (s) => s.ps.filter((p) => !p.bot);
const isSab = (p) => p && p.role === "S";
function bump(s) { s.ver = (s.ver || 0) + 1; }
function feed(s, text, k) { s.dirty = true; s.fid = (s.fid || 0) + 1; s.feed.push({ i: s.fid, t: text, k: k || "", at: s.now }); if (s.feed.length > 8) s.feed.splice(0, s.feed.length - 8); }
function exOf(p, s) { const c = CAST[p.look] || CAST.pf; return R.pick(s, c.ex); }
// ---------------------------------------------------------------------------
// The walk grid: 72 x 52 cells of 0.5 m, "#" blocked. Generated by
// tools/make_grid.mjs from the client's floor plan; do not edit by hand.
// ---------------------------------------------------------------------------

const CELL = 0.5, GW = 72, GD = 52;
const GRID = [
  "###################################################################.....",
  "#######################..##############....####...######...########.....",
  "#....................##..##############....####...######...########.....",
  "#....................##..##############......##...######...########.....",
  "#....................#####...................##...######...########.....",
  "#....................#####...######......###.##...######...########.....",
  "#....................#####...######......###.##............########.....",
  "#......................###...######......###.##............########.....",
  "#.....##########.......###...................#####.........########.....",
  "#.....##########.......###...............###.#####.....############.....",
  "#.....##########.......###..........##...###.#####.....############.....",
  "#...................................##...###...###.....######...........",
  "#..............................................###.....######...........",
  "#....................##......................##........######...........",
  "#....###########.....##......................##............##...........",
  "#....###########.....##......................###########################",
  "#....###########.....##......................###########################",
  "#....................####.....................##.......................#",
  "#....................####.....................##............####.......#",
  "#########..####################......###########............####.......#",
  "################################.....##########........................#",
  "####....######....#####......###.......................................#",
  "####..............#####.##.............................................#",
  "####..............#####.##..........................................##.#",
  "####..............#####.####........................................##.#",
  "####..............#####.####........................................##.#",
  "####..............#####................................................#",
  "####..............#####................................................#",
  "####..............#####................................................#",
  "####..............#####..............................................###",
  "####..............#####..............................................###",
  "####..............#####................................................#",
  "####..............#####.............................##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............###.........####################..##.................#",
  "####..............###.........####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "####..............#####.......####################..##.................#",
  "#######################.......####################..##.................#",
  "#######################.......####################..##.................#",
  "....................................................##.................#",
  "....................................................##.................#",
  ".......................................................................#",
  "..........................##............................######......####",
  "..........................##............................######......####",
  "..........................##........................................####",
  "########################################################################",
].join("");
// ---------------------------------------------------------------------------
// The house: walking, rooms, chore stations, spawn marks and meeting seats.
// ---------------------------------------------------------------------------

const W_HOUSE = GW * CELL, D_HOUSE = GD * CELL;

function blockedCell(i, j) { return i < 0 || j < 0 || i >= GW || j >= GD || GRID.charCodeAt(j * GW + i) === 35; }
function walkable(x, z) { return blockedCell(Math.floor(x / CELL), Math.floor(z / CELL)) === false; }
function inBounds(x, z) { return x >= 0 && z >= 0 && x <= W_HOUSE && z <= D_HOUSE; }

function nearestFree(x, z) {
  if (walkable(x, z)) return [x, z];
  for (let r = 0.5; r < 4; r += 0.25) for (let a = 0; a < 16; a++) {
    const px = x + Math.cos((a * Math.PI) / 8) * r, pz = z + Math.sin((a * Math.PI) / 8) * r;
    if (walkable(px, pz)) return [px, pz];
  }
  return [x, z];
}

function clearLine(a, b) {
  const d = Math.hypot(b[0] - a[0], b[1] - a[1]);
  const n = Math.ceil(d / (CELL * 0.5));
  for (let i = 1; i < n; i++) { const t = i / n; if (!walkable(a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t)) return false; }
  return true;
}

/** A* over the grid with string pulling. Returns [[x, z], ...] ending at `to`. */
function findPath(from, to) {
  const [fx, fz] = nearestFree(from[0], from[1]);
  const [tx, tz] = nearestFree(to[0], to[1]);
  const s0 = Math.floor(fz / CELL) * GW + Math.floor(fx / CELL), g = Math.floor(tz / CELL) * GW + Math.floor(tx / CELL);
  if (s0 === g) return [[tx, tz]];
  const gi = g % GW, gj = (g / GW) | 0;
  const h = (k) => Math.hypot((k % GW) - gi, ((k / GW) | 0) - gj);
  const open = [s0], came = {}, gs = { [s0]: 0 }, fs = { [s0]: h(s0) }, inOpen = { [s0]: 1 };
  let guard = 0, found = false;
  while (open.length && guard++ < 5000) {
    let bi = 0;
    for (let q = 1; q < open.length; q++) if (fs[open[q]] < fs[open[bi]]) bi = q;
    const cur = open[bi]; open[bi] = open[open.length - 1]; open.pop(); delete inOpen[cur];
    if (cur === g) { found = true; break; }
    const ci = cur % GW, cj = (cur / GW) | 0;
    for (let di = -1; di <= 1; di++) for (let dj = -1; dj <= 1; dj++) {
      if (!di && !dj) continue;
      const ni = ci + di, nj = cj + dj;
      if (blockedCell(ni, nj)) continue;
      if (di && dj && (blockedCell(ci + di, cj) || blockedCell(ci, cj + dj))) continue;
      const nk = nj * GW + ni;
      const t = gs[cur] + (di && dj ? 1.414 : 1);
      if (gs[nk] === undefined || t < gs[nk]) {
        came[nk] = cur; gs[nk] = t; fs[nk] = t + h(nk);
        if (!inOpen[nk]) { open.push(nk); inOpen[nk] = 1; }
      }
    }
  }
  if (!found) return [[tx, tz]];
  const cells = [];
  for (let k = g; k !== s0; k = came[k]) cells.push(k);
  cells.reverse();
  const pts = cells.map((k) => [(k % GW) * CELL + CELL / 2, ((k / GW) | 0) * CELL + CELL / 2]);
  pts[pts.length - 1] = [tx, tz];
  const out = [];
  let anchor = [fx, fz];
  for (let i = 0; i < pts.length; i++) {
    const next = pts[i + 1];
    if (next && clearLine(anchor, next)) continue;
    out.push([Math.round(pts[i][0] * 100) / 100, Math.round(pts[i][1] * 100) / 100]);
    anchor = pts[i];
  }
  return out;
}

const ROOM_RECTS = [
  ["hoh", 23, 0, 30, 8],
  ["gym", 11, 10, 16, 15],
  ["kitchen", 0, 0, 11, 10],
  ["lounge", 11, 0, 23, 10],
  ["bedroom", 0, 10, 11, 22],
  ["garden", 0, 8, 36, 26],
];
const ROOM_NAME = { lounge: "lounge", kitchen: "kitchen", garden: "garden", bedroom: "bedroom", gym: "gym", hoh: "HoH lounge" };
function roomAt(x, z) {
  for (const [id, x0, z0, x1, z1] of ROOM_RECTS) if (x >= x0 && x < x1 && z >= z0 && z < z1) return id;
  return "garden";
}

/**
 * Stations: where you stand to do something. game is the client mini-game,
 * dur the seconds it takes. Fix stations only matter during a sabotage.
 */
const STATIONS = {
  jollof: { kind: "task", label: "Stir the jollof", room: "kitchen", x: 3.6, z: 1.45, f: Math.PI, game: "stir", dur: 5 },
  plates: { kind: "task", label: "Wash the plates", room: "kitchen", x: 7.4, z: 1.45, f: Math.PI, game: "scrub", dur: 5 },
  fridge: { kind: "task", label: "Restock the fridge", room: "kitchen", x: 10.1, z: 1.5, f: Math.PI, game: "tapall", dur: 5 },
  money: { kind: "task", label: "Count the market money", room: "lounge", x: 16, z: 4.6, f: Math.PI, game: "order", dur: 5 },
  aerial: { kind: "task", label: "Fix the TV aerial", room: "lounge", x: 21.7, z: 1.9, f: Math.PI, game: "dial", dur: 5 },
  cushions: { kind: "task", label: "Arrange the cushions", room: "lounge", x: 13.3, z: 3.6, f: -Math.PI / 2, game: "tapall", dur: 4 },
  crown: { kind: "task", label: "Polish the HoH crown", room: "hoh", x: 26.5, z: 3.3, f: Math.PI, game: "scrub", dur: 4 },
  jacuzzi: { kind: "task", label: "Skim the jacuzzi", room: "hoh", x: 27, z: 7.2, f: Math.PI / 2, game: "tapall", dur: 5 },
  weights: { kind: "task", label: "Rack the weights", room: "gym", x: 15.2, z: 11.5, f: Math.PI, game: "rhythm", dur: 5 },
  laundry: { kind: "task", label: "Fold the laundry", room: "bedroom", x: 5.5, z: 11.4, f: Math.PI, game: "tapall", dur: 5 },
  beds: { kind: "task", label: "Make the beds", room: "bedroom", x: 3.1, z: 15.4, f: -Math.PI / 2, game: "order", dur: 4 },
  pool: { kind: "task", label: "Skim the pool", room: "garden", x: 20, z: 15.6, f: 0, game: "tapall", dur: 5 },
  plantain: { kind: "task", label: "Water the plantain", room: "garden", x: 14.6, z: 23.8, f: Math.PI, game: "hold", dur: 4 },
  sweep: { kind: "task", label: "Sweep the compound", room: "garden", x: 24.5, z: 12.6, f: Math.PI / 4, game: "scrub", dur: 5 },
  gen: { kind: "fix", label: "Fix the gen", room: "garden", x: 34.2, z: 15, f: Math.PI / 2, game: "pull", dur: 3 },
  gas1: { kind: "fix", label: "Close the gas valve", room: "kitchen", x: 0.95, z: 3, f: -Math.PI / 2, game: "hold", dur: 2 },
  gas2: { kind: "fix", label: "Close the gas valve", room: "garden", x: 34.9, z: 22, f: Math.PI / 2, game: "hold", dur: 2 },
  bell: { kind: "bell", label: "Ring Mama Eye's bell", room: "lounge", x: 18.6, z: 6.4, f: Math.PI, game: null, dur: 0 },
};
const TASK_IDS = Object.keys(STATIONS).filter((k) => STATIONS[k].kind === "task");
/** Chores anyone watching can see finished (a tick pops over your head). Saboteurs can only fake them. */
const VISUAL = new Set(["jollof", "weights", "sweep", "pool", "plantain"]);
const TASKS_EACH = 7;

/** Where everyone stands when a round starts or a meeting ends. */
const SPAWN = [
  [13.2, 7.2], [14.6, 8.6], [16, 7.2], [17.4, 8.6], [18.8, 7.2],
  [20.2, 8.6], [21.4, 7.2], [13.2, 9.2], [16, 9.3], [19.2, 9.3],
];
/** Meeting marks: the lounge sofas, the armchairs, and two standing spots. */
const SEATS = [
  [13.6, 1.35, 0], [14.8, 1.35, 0], [16, 1.35, 0], [17.2, 1.35, 0], [18.4, 1.35, 0],
  [12.35, 2.9, Math.PI / 2], [12.35, 4.2, Math.PI / 2], [21.1, 3, -Math.PI / 2], [21.1, 5.2, -Math.PI / 2], [16, 5.5, Math.PI],
];
// ---------------------------------------------------------------------------
// Lobby: seats, names, looks, settings, and starting a round.
// ---------------------------------------------------------------------------

function newPlayer(id, bot) {
  return {
    id, name: "Guest", look: null, bot: !!bot, on: true, ctl: bot ? "b" : "h", away: 0, hello: !!bot,
    x: SPAWN[0][0], z: SPAWN[0][1], f: 0, mv: 0, at: 0, tp: 0,
    alive: true, role: null, tasks: [], cd: 0, bell: 1, act: null, voted: null, deadAt: 0, known: false, ejected: false,
    spec: false, lastChat: 0, b: null,
  };
}

function freshState(ids, now) {
  return {
    v: 2, ver: 1, rng: hash(ids.join(",") + ":" + (now || 0)) || 1,
    phase: "LOBBY", now: now || 0, ends: 0, round: 0, pub: false, host: ids[0] || null,
    opts: { ...OPTS_DEFAULT }, fillAt: 0,
    ps: ids.map((id) => newPlayer(id, false)),
    bodies: [], sab: null, sabAt: 0, bellAt: 0, meet: null, res: null, end: null,
    feed: [], fid: 0, moved: false, cid: 0, stats: {},
  };
}

function freeLook(s, prefer) {
  const used = new Set(s.ps.filter((p) => p.look).map((p) => p.look));
  if (prefer && LOOKS.includes(prefer) && !used.has(prefer)) return prefer;
  return LOOKS.find((l) => !used.has(l)) || "pf";
}

function cleanName(raw) {
  let n = String(raw || "").replace(/[^\p{L}\p{N} ._'-]/gu, "").replace(/\s+/g, " ").trim().slice(0, 14);
  if (n.length < 2) return null;
  if (hasBadWord(n)) return null;
  return n;
}
function uniqueName(s, name, self) {
  const taken = new Set(s.ps.filter((p) => p !== self && p.hello).map((p) => p.name.toLowerCase()));
  if (!taken.has(name.toLowerCase())) return name;
  for (let i = 2; i < 20; i++) { const n = `${name.slice(0, 12)} ${i}`; if (!taken.has(n.toLowerCase())) return n; }
  return name;
}

function lobbyHumans(s) { return s.ps.filter((p) => !p.bot && p.hello); }

function hello(s, p, a) {
  const first = !s.ps.some((q) => q.hello && !q.bot);
  p.name = uniqueName(s, cleanName(a.name) || p.name, p);
  p.look = freeLook(s, a.look);
  p.hello = true;
  if (first && typeof a.room === "string") s.pub = a.room.startsWith("q-");
  if (!s.host || !pOf(s, s.host) || pOf(s, s.host).bot) s.host = p.id;
  if (s.phase === "LOBBY" && s.pub && !s.fillAt) s.fillAt = s.now + T.fill;
  if (s.phase === "LOBBY" && s.pub && lobbyHumans(s).length >= meta.maxPlayers) s.fillAt = Math.min(s.fillAt, s.now + T.fillFull);
  feed(s, `${p.name} joined the house.`, "join");
}

function setOpts(s, a) {
  for (const k of Object.keys(OPTS_ALLOWED)) if (k in a && OPTS_ALLOWED[k].includes(a[k])) s.opts[k] = a[k];
}

/** Fill empty seats with AI housemates, deal roles and chores, and open the round. */
function startRound(s) {
  s.rng = (hash(s.ps.map((p) => p.id).join(",") + ":" + s.now + ":" + s.round) ^ s.rng) >>> 0 || 1;
  // Anyone who never said hello (closed the tab on the menu) does not play.
  s.ps = s.ps.filter((p) => p.hello && p.on);
  for (const p of s.ps) { p.spec = false; p.bot = !!p.bot; }
  const target = Math.max(s.opts.fill, s.ps.length);
  const names = new Set(s.ps.map((p) => p.name.toLowerCase()));
  for (const look of BOT_ORDER) {
    if (s.ps.length >= Math.min(target, meta.maxPlayers)) break;
    if (s.ps.some((p) => p.look === look)) continue;
    const bot = newPlayer("ai-" + look, true);
    bot.look = look;
    let nm = CAST[look].name;
    if (names.has(nm.toLowerCase())) nm = nm + " (AI)";
    bot.name = nm; names.add(nm.toLowerCase());
    s.ps.push(bot);
  }
  const n = s.ps.length;
  const nS = s.opts.sabs || (n <= 6 ? 1 : 2);
  const order = R.shuffle(s, s.ps.map((p) => p.id));
  const sabs = new Set(order.slice(0, Math.min(nS, Math.max(1, Math.floor((n - 1) / 2)))));
  const spots = R.shuffle(s, SPAWN);
  s.ps.forEach((p, i) => {
    p.role = sabs.has(p.id) ? "S" : "H";
    p.alive = true; p.known = false; p.ejected = false; p.deadAt = 0;
    p.tasks = R.shuffle(s, TASK_IDS).slice(0, TASKS_EACH).map((id) => ({ id, done: false }));
    p.x = spots[i % spots.length][0]; p.z = spots[i % spots.length][1]; p.f = Math.PI; p.tp += 1; p.at = s.now;
    p.bell = 1; p.voted = null; p.act = null; p.mv = 0;
    p.b = p.ctl === "b" ? brainNew() : null;
  });
  s.round += 1;
  s.bodies = []; s.sab = null; s.meet = null; s.res = null; s.end = null; s.feed = []; s.flash = [];
  s.phase = "INTRO"; s.ends = s.now + T.intro;
  s.stats = { strikes: {}, tasks: {}, meetings: 0 };
  feed(s, `Mama Eye: Housemates, ${sabs.size === 1 ? "one of you is" : sabs.size + " of you are"} not who you say you are.`, "sys");
}

/** Intro over: everyone may move, and the Saboteurs' clocks start. */
function openPlay(s) {
  s.phase = "PLAY"; s.ends = 0; s.playAt = s.now;
  for (const p of s.ps) if (isSab(p)) p.cd = s.now + T.firstKill;
  s.sabAt = s.now + T.sabFirst;
  s.bellAt = s.now + T.bellLock;
}

/** Back to the lobby with the same people (AI housemates leave). */
function toLobby(s) {
  s.ps = s.ps.filter((p) => !p.bot && p.on);
  for (const p of s.ps) {
    p.role = null; p.alive = true; p.tasks = []; p.spec = false; p.ctl = "h"; p.b = null; p.voted = null; p.act = null; p.known = false; p.ejected = false;
  }
  if (!s.ps.some((p) => p.id === s.host)) s.host = s.ps[0] ? s.ps[0].id : null;
  s.phase = "LOBBY"; s.ends = 0; s.bodies = []; s.sab = null; s.meet = null; s.res = null; s.end = null;
  s.fillAt = s.pub && s.ps.length ? s.now + T.fill : 0;
  s.feed = [];
}
// ---------------------------------------------------------------------------
// Play: moving, chores, strikes, reports, the bell, sabotage, vision, winning.
// ---------------------------------------------------------------------------

function visionOf(s, p) {
  if (!p.alive || p.spec) return Infinity;
  if (isSab(p)) return VISION.S;
  return s.sab && s.sab.k === "nepa" ? VISION.nepa : VISION.H;
}

/** Can `viewer` see the point (x, z)? Walls cut sight: other rooms need to be close. */
function seesPoint(s, viewer, x, z) {
  const r = visionOf(s, viewer);
  if (r === Infinity) return true;
  const d = Math.hypot(viewer.x - x, viewer.z - z);
  if (d > r) return false;
  return d <= VISION.close || roomAt(viewer.x, viewer.z) === roomAt(x, z);
}
function sees(s, viewer, other) {
  if (viewer.id === other.id) return true;
  if (!other.alive && viewer.alive) return false; // ghosts are invisible to the living
  return seesPoint(s, viewer, other.x, other.z);
}

function checkMove(s, p, a) {
  if (s.phase !== "PLAY") return "not now";
  if (p.spec) return "spectating";
  const { x, z } = a;
  if (typeof x !== "number" || typeof z !== "number" || !Number.isFinite(x) || !Number.isFinite(z)) return "bad move";
  if (!inBounds(x, z)) return "bad move";
  if (p.alive && !walkable(x, z)) return "bad move";
  const dt = Math.max(0.05, ((a._now || s.now) - (p.at || 0)) / 1000);
  const d = Math.hypot(x - p.x, z - p.z);
  const limit = (p.alive ? SPEED.maxHuman : SPEED.maxHuman * 1.6) * Math.min(dt, 2) + SPEED.slack;
  if (d > limit) return "bad move";
  return null;
}
function applyMove(s, p, a) {
  const d = Math.hypot(a.x - p.x, a.z - p.z);
  p.x = Math.round(a.x * 100) / 100; p.z = Math.round(a.z * 100) / 100;
  if (typeof a.f === "number" && Number.isFinite(a.f)) p.f = Math.round(a.f * 100) / 100;
  p.mv = d > 0.01 ? 1 : 0;
  p.at = a._now || s.now;
  if (p.act && dist(p, STATIONS[p.act.id]) > RANGE.use + 0.6) p.act = null;
  s.moved = true;
}

function nearStation(p, id, range) { const st = STATIONS[id]; return st && Math.hypot(p.x - st.x, p.z - st.z) <= (range || RANGE.use); }
function myTask(p, id) { return p.tasks.find((t) => t.id === id) || null; }

function stationOpen(s, p, id) {
  const st = STATIONS[id];
  if (!st) return "no such station";
  if (st.kind === "task") {
    const t = myTask(p, id);
    if (!t) return "That's not one of your chores.";
    if (t.done) return "Already done.";
    return null;
  }
  if (st.kind === "fix") {
    if (!p.alive) return "Ghosts can't fix that.";
    if (!s.sab) return "Nothing to fix.";
    if (id === "gen" && s.sab.k !== "nepa") return "The gen is fine.";
    if ((id === "gas1" || id === "gas2") && (s.sab.k !== "gas" || s.sab.fixed.includes(id))) return "This valve is fine.";
    return null;
  }
  return "Use the bell button.";
}

function finishStation(s, p, id) {
  const st = STATIONS[id];
  p.act = null;
  s.dirty = true;
  if (st.kind === "task") {
    const t = myTask(p, id);
    t.done = true;
    if (!isSab(p)) {
      s.stats.tasks[p.id] = (s.stats.tasks[p.id] || 0) + 1;
      if (VISUAL.has(id) && p.alive) {
        const saw = living(s).filter((w) => w.id !== p.id && sees(s, w, p));
        s.flash = (s.flash || []).filter((f) => s.now - f.at < 3000);
        s.fl = (s.fl || 0) + 1;
        s.flash.push({ i: s.fl, id: p.id, st: id, at: s.now, to: saw.map((w) => w.id) });
        for (const w of saw) if (w.b) { w.b.sus[p.id] = Math.min(0, (w.b.sus[p.id] || 0)) - 25; w.b.clear[p.id] = id; }
      }
      checkWin(s);
    }
    return;
  }
  if (id === "gen") { s.sab = null; s.sabAt = Math.max(s.sabAt, s.now + T.sabCd); feed(s, `${p.name} fixed the gen. Light don come back!`, "fix"); return; }
  s.sab.fixed.push(id);
  if (s.sab.fixed.length >= 2) { s.sab = null; s.sabAt = Math.max(s.sabAt, s.now + T.sabCd); feed(s, "Both gas valves closed. The house can breathe.", "fix"); }
}

function taskBar(s) {
  let all = 0, done = 0;
  for (const p of playing(s)) if (!isSab(p)) for (const t of p.tasks) { all += 1; if (t.done) done += 1; }
  return all ? done / all : 0;
}

function canStrike(s, p, target) {
  if (s.phase !== "PLAY") return "not now";
  if (!isSab(p) || !p.alive) return "You can't do that.";
  if (s.now < p.cd) return "Not yet.";
  if (!target || !target.alive || target.spec || isSab(target)) return "No target.";
  if (dist(p, target) > RANGE.strike) return "Too far.";
  return null;
}
function strike(s, p, target) {
  s.dirty = true;
  target.alive = false; target.deadAt = s.now; target.act = null;
  s.bodies.push({ id: target.id, x: target.x, z: target.z, at: s.now, by: p.id });
  p.cd = s.now + s.opts.kill * 1000;
  s.stats.strikes[p.id] = (s.stats.strikes[p.id] || 0) + 1;
  // Bots in sight may notice.
  for (const w of living(s)) {
    if (w.id === p.id || w.id === target.id || !w.b) continue;
    if (sees(s, w, p) && R.chance(s, isSab(w) ? 1 : 0.7)) w.b.saw.push({ k: "strike", who: p.id, victim: target.id, room: roomAt(p.x, p.z), at: s.now });
  }
  checkWin(s);
}

function bodyNear(s, p) {
  let best = null, bd = Infinity;
  for (const b of s.bodies) { const d = Math.hypot(b.x - p.x, b.z - p.z); if (d <= RANGE.report && d < bd) { best = b; bd = d; } }
  return best;
}

function canSabotage(s, p, k) {
  if (s.phase !== "PLAY") return "not now";
  if (!isSab(p)) return "You can't do that.";
  if (k !== "nepa" && k !== "gas") return "bad sabotage";
  if (s.sab) return "A sabotage is already on.";
  if (s.now < s.sabAt) return "Not yet.";
  return null;
}
function sabotage(s, p, k) {
  s.sab = { k, at: s.now, ends: k === "gas" ? s.now + T.gas : 0, fixed: [], by: p.id };
  s.sabAt = s.now + T.sabCd;
  feed(s, k === "nepa" ? "NEPA has taken light! Fix the gen in the garden." : "Gas leak! Close both valves before the house fills up!", "sab");
}

function checkWin(s) {
  if (s.phase === "END" || s.phase === "LOBBY") return;
  const live = living(s);
  const S = live.filter(isSab).length, H = live.length - S;
  if (S === 0) return endGame(s, "H", "Every Saboteur is out of the house.");
  if (S >= H) return endGame(s, "S", "The Saboteurs took over the house.");
  if (taskBar(s) >= 1) return endGame(s, "H", "The house finished every chore.");
}

function endGame(s, win, why) {
  s.phase = "END"; s.ends = s.now + T.endBack; s.sab = null; s.meet = null;
  s.end = { win, why, at: s.now };
  feed(s, why, "end");
}

/** Every tick while playing: sabotage clocks and dropped players. */
function tickPlay(s) {
  if (s.sab && s.sab.k === "gas" && s.now >= s.sab.ends) endGame(s, "S", "The gas leak emptied the house. Saboteurs win.");
}
// ---------------------------------------------------------------------------
// House meetings: chat, votes, and the eviction.
// ---------------------------------------------------------------------------

/**
 * One-tap lines. {name} and {room} are filled from the action. Shared with the
 * client by index, so only append to this list.
 */
const QUICK = [
  "Where was the body?",
  "I was in the {room}.",
  "I saw {name} near the body!",
  "{name} is sus.",
  "{name} was with me. Clear.",
  "I was doing my chores.",
  "Skip am. No evidence.",
  "Vote {name}!",
  "Na lie!",
  "No be me o!",
  "Who called this meeting?",
  "I fixed the gen.",
  "Watch the task bar.",
  "Ehen?! Explain yourself, {name}.",
  "I saw {name} in the {room}.",
  "Trust me abeg.",
];
const QUICK_NEEDS = QUICK.map((q) => ({ name: q.includes("{name}"), room: q.includes("{room}") }));

/** Whole words that are starred, and stems starred inside any word. Names like Dickson or Shitta stay. */
const BAD = [
  "fuk", "fck", "shit", "bitch", "dick", "pussy", "asshole", "bastard", "slut", "fag", "retard", "rape", "porn",
  "ashawo", "ashewo", "olosho", "oloshi", "dickhead", "mf", "toto", "prick", "wanker", "twat", "penis", "vagina",
].map(collapse);
const BAD_STEM = ["fuck", "cunt", "nigg", "fagot", "motherf", "bitch", "whore"].map(collapse);
const LEET = { "0": "o", "1": "i", "3": "e", "4": "a", "5": "s", "7": "t", "@": "a", "$": "s", "!": "i" };
function collapse(w) { return w.replace(/(.)\1+/g, "$1"); }
function norm(w) { return collapse(w.toLowerCase().split("").map((c) => LEET[c] || c).join("").replace(/[^a-z]/g, "")); }
function badWord(w) { const n = norm(w); if (n.length < 2) return false; return BAD.includes(n) || BAD.includes(n.replace(/s$/, "")) || BAD_STEM.some((b) => n.includes(b)); }
function hasBadWord(text) { return String(text).split(/\s+/).some(badWord); }
/** Swear filter and link stripper for typed chat. */
function cleanChat(raw) {
  let t = String(raw || "").replace(/[\u0000-\u001f\u007f]/g, " ").replace(/\s+/g, " ").trim().slice(0, 100);
  t = t.replace(/\b(https?:\/\/|www\.)\S+/gi, "[link]").replace(/\b\S+\.(com|ng|net|org|io|ly|co|me|xyz|app)\b\S*/gi, "[link]");
  t = t.split(" ").map((w) => (badWord(w) ? "*".repeat(Math.min(6, w.length)) : w)).join(" ");
  return t;
}

function startMeeting(s, by, kind, bodyId) {
  s.stats.meetings += 1;
  const reporter = pOf(s, by);
  const body = s.bodies.find((x) => x.id === bodyId);
  const where = body ? roomAt(body.x, body.z) : reporter ? roomAt(reporter.x, reporter.z) : null;
  // Everyone learns who is dead; bodies are cleared away.
  for (const p of s.ps) if (!p.alive) p.known = true;
  s.bodies = [];
  if (s.sab && s.sab.k === "nepa") s.sab = null;
  const order = R.shuffle(s, living(s).map((p) => p.id));
  order.forEach((id, i) => { const p = pOf(s, id); const seat = SEATS[i % SEATS.length]; p.x = seat[0]; p.z = seat[1]; p.f = seat[2]; p.tp += 1; p.act = null; p.mv = 0; p.at = s.now; });
  for (const p of s.ps) p.voted = null;
  s.meet = { by, kind, body: bodyId || null, room: where, at: s.now, chat: [], seats: order };
  s.phase = "MEET"; s.ends = s.now + s.opts.discuss * 1000;
  feed(s, kind === "body" ? `${reporter ? reporter.name : "Someone"} found ${nameOf(s, bodyId)}'s body!` : `${reporter ? reporter.name : "Someone"} rang Mama Eye's bell!`, "meet");
  botsPlanMeeting(s);
}
function nameOf(s, id) { const p = pOf(s, id); return p ? p.name : "someone"; }

function chatLine(s, p, text, extra) {
  s.dirty = true;
  s.cid += 1;
  s.meet.chat.push(Object.assign({ i: s.cid, w: p.id, t: text, g: p.alive ? 0 : 1, at: s.now }, extra || {}));
  if (s.meet.chat.length > 60) s.meet.chat.splice(0, s.meet.chat.length - 60);
  p.lastChat = s.now;
}

function checkChat(s, p, a) {
  if (s.phase !== "MEET" && s.phase !== "VOTE") return "Chat opens at House Meetings.";
  if (p.spec) return "spectating";
  if (s.now - (p.lastChat || 0) < 1200) return "Slow down small.";
  if (a.q !== undefined) {
    if (!Number.isInteger(a.q) || a.q < 0 || a.q >= QUICK.length) return "bad line";
    const need = QUICK_NEEDS[a.q];
    if (need.name && !(typeof a.who === "string" && pOf(s, a.who))) return "Pick who.";
    if (need.room && !(typeof a.room === "string" && ROOM_NAME[a.room])) return "Pick where.";
    return null;
  }
  if (typeof a.text !== "string" || !a.text.trim()) return "Say something.";
  if (a.text.length > 140) return "Too long.";
  return null;
}
function applyChat(s, p, a) {
  if (a.q !== undefined) {
    const text = QUICK[a.q].replace(/\{name\}/g, a.who ? nameOf(s, a.who) : "").replace(/\{room\}/g, a.room ? ROOM_NAME[a.room] : "");
    chatLine(s, p, text, { q: a.q, about: a.who || null });
  } else {
    const text = cleanChat(a.text);
    if (!text) return;
    chatLine(s, p, text);
  }
  if (p.alive) botsHear(s, s.meet.chat[s.meet.chat.length - 1]);
}

function checkVote(s, p, a) {
  if (s.phase !== "VOTE") return "Voting has not started.";
  if (!p.alive || p.spec) return "Only living housemates vote.";
  if (p.voted) return "You already voted.";
  if (a.who !== "skip") { const t = pOf(s, a.who); if (!t || !t.alive || t.spec) return "Pick a living housemate."; }
  return null;
}
function applyVote(s, p, who) {
  s.dirty = true;
  p.voted = who;
  if (living(s).every((q) => q.voted)) s.ends = Math.min(s.ends, s.now + 1500);
}

function openVote(s) { s.phase = "VOTE"; s.ends = s.now + s.opts.vote * 1000; botsPlanVotes(s); }

function closeVote(s) {
  const tally = {};
  let skips = 0;
  for (const p of living(s)) {
    if (!p.voted || p.voted === "skip") { skips += 1; continue; }
    (tally[p.voted] = tally[p.voted] || []).push(p.id);
  }
  let top = null, topN = 0, tie = false;
  for (const [id, list] of Object.entries(tally)) {
    if (list.length > topN) { top = id; topN = list.length; tie = false; } else if (list.length === topN) tie = true;
  }
  let out = null;
  if (top && !tie && topN > skips) out = top;
  s.res = { out, tally, skips, tie: !!tie && topN > 0, role: null, at: s.now };
  if (out) {
    const p = pOf(s, out);
    p.alive = false; p.ejected = true; p.known = true; p.deadAt = s.now; p.act = null;
    s.res.role = p.role;
    feed(s, `${p.name} was evicted.`, "evict");
  } else feed(s, tie ? "It's a tie. Nobody leaves." : "The house skipped. Nobody leaves.", "evict");
  s.phase = "RESULT"; s.ends = s.now + T.result;
}

/** After the reveal: win check, then everyone back to the lounge and on with it. */
function afterResult(s) {
  s.meet = null;
  checkWin(s);
  if (s.phase === "END") return;
  const spots = R.shuffle(s, SPAWN);
  living(s).forEach((p, i) => { p.x = spots[i % spots.length][0]; p.z = spots[i % spots.length][1]; p.f = Math.PI; p.tp += 1; p.at = s.now; });
  for (const p of s.ps) if (isSab(p)) p.cd = s.now + s.opts.kill * 1000;
  s.sabAt = Math.max(s.sabAt, s.now + T.sabCd / 2);
  s.bellAt = s.now + T.bellLock;
  s.res = null;
  s.phase = "PLAY"; s.ends = 0;
}
// ---------------------------------------------------------------------------
// AI housemates. They only know what they have seen or heard: bots never read
// roles they should not know. They walk the same grid humans do.
// ---------------------------------------------------------------------------

function brainNew() {
  return { goal: null, gk: null, path: [], until: 0, doing: null, seen: {}, saw: [], sus: {}, clear: {}, plan: [], voteAt: 0, hunt: null, rethink: 0, reportBody: null, reportAt: 0, rooms: [], defended: 0, idleUntil: 0, vouched: {} };
}

function setGoal(s, p, xz, key) {
  const b = p.b;
  b.path = findPath([p.x, p.z], xz);
  b.goal = xz; b.gk = key; b.doing = null;
}

function stepAlong(s, p, dt) {
  const b = p.b;
  if (!b.path.length) { p.mv = 0; return true; }
  let left = SPEED.walk * dt;
  while (left > 0 && b.path.length) {
    const [tx, tz] = b.path[0];
    const dx = tx - p.x, dz = tz - p.z, d = Math.hypot(dx, dz);
    if (d <= left) { p.x = tx; p.z = tz; b.path.shift(); left -= d; if (d > 0.001) p.f = Math.atan2(dx, dz); }
    else { p.x += (dx / d) * left; p.z += (dz / d) * left; p.f = Math.atan2(dx, dz); left = 0; }
  }
  p.x = Math.round(p.x * 100) / 100; p.z = Math.round(p.z * 100) / 100; p.f = Math.round(p.f * 100) / 100;
  p.mv = 1; p.at = s.now; s.moved = true;
  return !b.path.length;
}

/** Pick what to do next: a chore, a fake chore, or a wander. */
function nextChore(s, p) {
  const b = p.b;
  const open = p.tasks.filter((t) => !t.done);
  if (open.length && R.chance(s, isSab(p) ? 0.75 : 0.8)) {
    // Housemates like company: sometimes pick a chore in a room where people are.
    if (!isSab(p) && R.chance(s, 0.35)) {
      const busy = new Set(Object.values(b.seen).filter((v) => s.now - v.at < 8000).map((v) => v.room));
      const social = open.filter((t) => busy.has(STATIONS[t.id].room));
      if (social.length) { const id = R.pick(s, social).id; setGoal(s, p, [STATIONS[id].x, STATIONS[id].z], "task:" + id); return; }
    }
    // Nearest of a couple of random picks: feels purposeful without being a robot.
    const picks = R.shuffle(s, open).slice(0, 2).map((t) => t.id);
    picks.sort((a, c) => Math.hypot(STATIONS[a].x - p.x, STATIONS[a].z - p.z) - Math.hypot(STATIONS[c].x - p.x, STATIONS[c].z - p.z));
    const id = picks[0];
    setGoal(s, p, [STATIONS[id].x, STATIONS[id].z], "task:" + id);
    return;
  }
  const id = R.pick(s, Object.keys(STATIONS));
  const st = STATIONS[id];
  setGoal(s, p, nearestFree(st.x + R.range(s, -1.5, 1.5), st.z + R.range(s, -1.5, 1.5)), "wander");
}

function witnessesOf(s, sab, target) {
  return living(s).filter((w) => w.id !== sab.id && w.id !== target.id && !isSab(w) && (sees(s, w, sab) || sees(s, w, target))).length;
}

function sabThink(s, p) {
  const b = p.b;
  // A body you made: sometimes walk off, sometimes cry wolf.
  if (s.now >= p.cd && !b.doing) {
    const targets = living(s).filter((q) => !isSab(q) && Math.hypot(q.x - p.x, q.z - p.z) < 11);
    let best = null;
    for (const q of targets) if (witnessesOf(s, p, q) === 0 && (!best || dist(p, q) < dist(p, best))) best = q;
    if (best) {
      if (dist(p, best) <= RANGE.strike) {
        if (R.chance(s, 0.55)) {
          strike(s, p, best);
          b.hunt = null;
          if (s.phase !== "PLAY") return;
          if (R.chance(s, 0.18)) { b.reportBody = best.id; b.reportAt = s.now + R.range(s, 1500, 3500); }
          else { const far = R.pick(s, TASK_IDS); setGoal(s, p, [STATIONS[far].x, STATIONS[far].z], "flee"); }
          return;
        }
      } else if (!b.hunt || b.hunt !== best.id || s.now >= b.rethink) {
        b.hunt = best.id; b.rethink = s.now + 900;
        setGoal(s, p, [best.x, best.z], "hunt");
      }
    } else if (b.hunt) { b.hunt = null; b.path = []; }
    // Nobody alone? Cut the light and try again in the dark.
    if (!best && !s.sab && s.now >= s.sabAt && R.chance(s, 0.03)) sabotage(s, p, "nepa");
  }
  if (!s.sab && s.now >= s.sabAt && R.chance(s, 0.006)) {
    const k = R.chance(s, 0.3) && s.now - (s.playAt || 0) > 50000 && living(s).filter((q) => !isSab(q)).length >= 3 ? "gas" : "nepa";
    sabotage(s, p, k);
  }
}

/** Send the nearest housemate bots to fix a sabotage. */
function assignFixers(s) {
  if (!s.sab || s.sab.assigned) return;
  const pool = living(s).filter((p) => p.ctl === "b" && !isSab(p));
  const stations = s.sab.k === "nepa" ? ["gen"] : ["gas1", "gas2"];
  const used = new Set();
  s.sab.assigned = {};
  for (const id of stations) {
    const st = STATIONS[id];
    const order = pool.filter((p) => !used.has(p.id)).sort((a, c) => Math.hypot(a.x - st.x, a.z - st.z) - Math.hypot(c.x - st.x, c.z - st.z));
    for (const p of order.slice(0, s.sab.k === "nepa" ? 2 : 1)) { used.add(p.id); s.sab.assigned[p.id] = id; setGoal(s, p, [st.x, st.z], "fix:" + id); }
  }
}

function botPerceive(s, p) {
  const b = p.b;
  const room = roomAt(p.x, p.z);
  if (!b.rooms.length || b.rooms[b.rooms.length - 1].room !== room) { b.rooms.push({ room, at: s.now }); if (b.rooms.length > 6) b.rooms.shift(); }
  for (const q of living(s)) if (q.id !== p.id && sees(s, p, q)) b.seen[q.id] = { room: roomAt(q.x, q.z), at: s.now };
  if (b.reportBody) return;
  for (const body of s.bodies) {
    if (!seesPoint(s, p, body.x, body.z)) continue;
    if (isSab(p)) continue; // Saboteurs walk past bodies they did not plan to report.
    b.reportBody = body.id; b.reportAt = s.now + R.range(s, 500, 1600);
    break;
  }
}

function botPlay(s, p, dt) {
  const b = p.b;
  if (p.alive) botPerceive(s, p);
  // Report a body once you reach it.
  if (b.reportBody && p.alive && s.now >= b.reportAt) {
    const body = s.bodies.find((x) => x.id === b.reportBody);
    if (!body) b.reportBody = null;
    else if (Math.hypot(body.x - p.x, body.z - p.z) <= RANGE.report) {
      for (const q of living(s)) if (q.id !== p.id && sees(s, p, q) && Math.hypot(q.x - body.x, q.z - body.z) < 6) b.sus[q.id] = (b.sus[q.id] || 0) + 12;
      startMeeting(s, p.id, "body", body.id);
      return;
    }
    else if (b.gk !== "body") setGoal(s, p, [body.x, body.z], "body");
  }
  if (p.alive && isSab(p)) { sabThink(s, p); if (s.phase !== "PLAY") return; }
  if (s.sab && s.sab.assigned && s.sab.assigned[p.id] && !(b.gk || "").startsWith("fix:")) {
    const id = s.sab.assigned[p.id];
    setGoal(s, p, [STATIONS[id].x, STATIONS[id].z], "fix:" + id);
  }
  // Doing something at a station.
  if (b.doing) {
    if (s.now < b.until) { p.mv = 0; return; }
    const id = b.doing; b.doing = null;
    if (STATIONS[id].kind === "task" && myTask(p, id) && !myTask(p, id).done && nearStation(p, id)) finishStation(s, p, id);
    else if (STATIONS[id].kind === "fix" && !stationOpen(s, p, id) && nearStation(p, id)) finishStation(s, p, id);
    if (s.phase !== "PLAY") return;
    b.gk = null; b.idleUntil = s.now + R.range(s, 1500, 5000);
    return;
  }
  if (!b.path.length && s.now < b.idleUntil) { p.mv = 0; return; }
  const arrived = stepAlong(s, p, dt);
  if (!arrived) return;
  const gk = b.gk || "";
  if (gk.startsWith("task:") || gk.startsWith("fix:")) {
    const id = gk.split(":")[1];
    const st = STATIONS[id];
    if (st.kind === "fix" && stationOpen(s, p, id)) { b.gk = null; return; }
    p.f = st.f;
    b.doing = id; b.until = s.now + st.dur * 1000 * R.range(s, 1.05, 1.5);
    p.mv = 0;
    return;
  }
  if (gk === "hunt" || gk === "body") { b.gk = null; return; }
  b.gk = null;
  b.idleUntil = s.now + R.range(s, 400, 2500);
  nextChore(s, p);
}

/** Drive every AI-controlled body for one tick of `dt` seconds. */
function tickBots(s, dt) {
  if (s.phase !== "PLAY") return;
  assignFixers(s);
  for (const p of s.ps) {
    if (p.ctl !== "b" || p.spec) continue;
    if (!p.b) p.b = brainNew();
    if (!p.alive && isSab(p)) { if (!p.b.path.length && R.chance(s, 0.02)) nextChore(s, p); else stepAlong(s, p, dt); continue; }
    botPlay(s, p, dt);
    if (s.phase !== "PLAY") return;
  }
}

// ---------------------------------------------------------------------------
// Meetings: what bots say and how they vote.
// ---------------------------------------------------------------------------

const ROOMS_SAID = (r) => ROOM_NAME[r] || "house";

function say(s, p, at, text, about, k) { p.b.plan.push({ at, text, about: about || null, k: k || null }); }

function botsPlanMeeting(s) {
  const m = s.meet;
  const victim = m.body ? pOf(s, m.body) : null;
  const where = ROOMS_SAID(m.room);
  for (const p of living(s)) {
    if (p.ctl !== "b") continue;
    const b = p.b || (p.b = brainNew());
    b.plan = []; b.path = []; b.doing = null; b.hunt = null; b.reportBody = null; b.voteAt = 0;
    let t = s.now + R.range(s, 1500, 4000);
    const ex = exOf(p, s);
    if (m.by === p.id) {
      if (m.kind === "body") say(s, p, s.now + R.range(s, 900, 2000), `${ex} Body for the ${where}! Na ${victim ? victim.name : "somebody"}.`);
      else say(s, p, s.now + R.range(s, 900, 2000), "I ring the bell because something no dey add up.");
      t += 2500;
    }
    // What this bot actually saw.
    const sawIt = b.saw.find((w) => w.k === "strike" && pOf(s, w.who) && pOf(s, w.who).alive && !isSab(p));
    if (sawIt) {
      const killer = pOf(s, sawIt.who);
      b.sus[killer.id] = 200;
      say(s, p, t, `I SEE AM! ${killer.name} strike ${nameOf(s, sawIt.victim)} for the ${ROOMS_SAID(sawIt.room)}! Vote ${killer.name}!`, killer.id, "ev");
      continue;
    }
    if (isSab(p)) {
      const others = living(s).filter((q) => q.id !== p.id && !isSab(q));
      if (R.chance(s, 0.5) && others.length) {
        const mark = R.pick(s, others);
        b.sus[mark.id] = (b.sus[mark.id] || 0) + 30;
        say(s, p, t, R.pick(s, [`${mark.name} dey move sus. Always following people around.`, `Where was ${mark.name}? I never see them doing any chore.`, `${mark.name} was close to the ${where}. Just saying.`]), mark.id, "acc");
      } else {
        const last = b.rooms.length ? b.rooms[b.rooms.length - 1].room : "lounge";
        say(s, p, t, R.pick(s, [`I was in the ${ROOMS_SAID(last)} doing my chores.`, "No be me o. I was busy with my chores.", "Skip am. We no get evidence."]));
      }
      continue;
    }
    // Housemates: who was last seen with the victim, and who was near the body's room lately?
    const vs = victim && b.seen[victim.id];
    const sameRoom = vs && vs.room === m.room;
    const withVictim = vs && s.now - vs.at < (sameRoom ? 60000 : 30000) ? Object.entries(b.seen).filter(([id, v]) => id !== p.id && id !== victim.id && v.room === vs.room && Math.abs(v.at - vs.at) < 12000 && pOf(s, id) && pOf(s, id).alive && !b.clear[id]).map(([id]) => id) : [];
    for (const id of withVictim) b.sus[id] = (b.sus[id] || 0) + (sameRoom ? (withVictim.length === 1 ? 40 : 18) : 8);
    const near = Object.entries(b.seen).filter(([id, v]) => id !== p.id && v.room === m.room && s.now - v.at < 25000 && pOf(s, id) && pOf(s, id).alive).map(([id]) => id);
    for (const id of near) b.sus[id] = (b.sus[id] || 0) + 10;
    if (withVictim.length && (sameRoom || R.chance(s, 0.3)) && R.chance(s, 0.85)) {
      const id = withVictim.length === 1 ? withVictim[0] : R.pick(s, withVictim);
      say(s, p, t, R.pick(s, [`I last saw ${victim.name} with ${nameOf(s, id)} in the ${ROOMS_SAID(vs.room)}.`, `${nameOf(s, id)}, you were with ${victim.name} in the ${ROOMS_SAID(vs.room)}. Explain.`]), id, sameRoom ? "ev" : "acc");
    } else if (m.kind === "body" && near.length && R.chance(s, 0.8)) {
      const id = R.pick(s, near);
      say(s, p, t, R.pick(s, [`${nameOf(s, id)} was around the ${where} just now.`, `I saw ${nameOf(s, id)} near the ${where}. Hmm.`]), id, "acc");
    } else if (R.chance(s, 0.65)) {
      const last = b.rooms.length ? b.rooms[b.rooms.length - 1].room : "lounge";
      say(s, p, t, R.pick(s, [`I was in the ${ROOMS_SAID(last)}.`, `I was doing chores in the ${ROOMS_SAID(last)}.`, "Who was alone just now?", "Skip am if nobody see anything."]));
    }
  }
}

const ACCUSE_RE = /\b(sus|vote|saw|see am|kill|strike|struck|liar|lie|lying|did it|na (him|her|am)|guilty|fake)\b/i;
const VOUCH_RE = /\b(clear|safe|with me|innocent|not (him|her)|trust)\b/i;

/** Bots weigh what is said in meetings, and defend themselves when named. */
function botsHear(s, line) {
  if (!line || line.g) return;
  const speaker = pOf(s, line.w);
  const named = [];
  if (line.about) named.push(line.about);
  else {
    const low = ` ${line.t.toLowerCase()} `;
    for (const p of s.ps) if (p.id !== line.w && p.name.length >= 2 && low.includes(p.name.toLowerCase())) named.push(p.id);
  }
  if (!named.length) return;
  const q = line.q;
  // How much a line moves suspicion: evidence > accusation > a defensive "na lie".
  let weight;
  if (line.k) weight = { ev: 18, acc: 7, def: 3, vouch: -14 }[line.k] || 0;
  else if (q !== undefined) weight = { 2: 14, 14: 8, 3: 6, 7: 6, 13: 5, 4: -10 }[q] || 2;
  else weight = /\b(saw|see am|with|caught)\b/i.test(line.t) && ACCUSE_RE.test(line.t) ? 12 : ACCUSE_RE.test(line.t) ? 7 : VOUCH_RE.test(line.t) ? -10 : 2;
  const accuse = weight >= 5, vouch = weight < 0;
  for (const p of living(s)) {
    if (p.ctl !== "b" || p.id === line.w) continue;
    const b = p.b || (p.b = brainNew());
    const trust = (b.sus[line.w] || 0) > 40 ? 0.4 : 1;
    for (const id of named) {
      if (id === p.id) {
        if (accuse && s.now - b.defended > 4000) {
          b.defended = s.now;
          const last = b.rooms.length ? b.rooms[b.rooms.length - 1].room : "lounge";
          say(s, p, s.now + R.range(s, 1200, 2600), R.pick(s, [`Me?! I was in the ${ROOMS_SAID(last)}!`, `${exOf(p, s)} Na lie! ${speaker ? speaker.name : "You"} dey find who to blame.`, `No be me o! Check the ${ROOMS_SAID(last)}.`]), line.w, "def");
          b.sus[line.w] = (b.sus[line.w] || 0) + 10;
        }
        continue;
      }
      if (isSab(p)) { if (accuse) b.sus[id] = (b.sus[id] || 0) + weight; continue; }
      if (b.clear[id]) {
        if (accuse && !b.vouched[id] && pOf(s, id) && pOf(s, id).alive) {
          b.vouched[id] = 1;
          say(s, p, s.now + R.range(s, 1500, 3000), `${nameOf(s, id)} is clear. I watched them finish the ${STATIONS[b.clear[id]].label.toLowerCase().replace(/^\w+ /, "")}.`, id, "vouch");
        }
        continue;
      }
      b.sus[id] = (b.sus[id] || 0) + weight * (weight > 0 ? trust : 1);
    }
  }
}

function botsPlanVotes(s) {
  const span = Math.max(3000, s.opts.vote * 1000 * 0.7);
  for (const p of living(s)) if (p.ctl === "b") p.b.voteAt = s.now + R.range(s, 1500, span);
}

function botChoose(s, p) {
  const b = p.b;
  const cands = living(s).filter((q) => q.id !== p.id);
  if (isSab(p)) {
    const heat = {};
    for (const line of (s.meet && s.meet.chat) || []) if (line.about) heat[line.about] = (heat[line.about] || 0) + 1;
    const hs = cands.filter((q) => !isSab(q)).sort((a, c) => ((heat[c.id] || 0) + (b.sus[c.id] || 0) / 20) - ((heat[a.id] || 0) + (b.sus[a.id] || 0) / 20));
    if (hs.length && ((heat[hs[0].id] || 0) >= 1 || (b.sus[hs[0].id] || 0) >= 25)) return hs[0].id;
    return R.chance(s, 0.6) || !hs.length ? "skip" : R.pick(s, hs).id;
  }
  const ranked = cands.slice().sort((a, c) => (b.sus[c.id] || 0) - (b.sus[a.id] || 0));
  const top = ranked.length ? b.sus[ranked[0].id] || 0 : 0, second = ranked.length > 1 ? b.sus[ranked[1].id] || 0 : 0;
  if (top >= 25 && top - second >= 8) return ranked[0].id;
  if (top >= 15 && top - second >= 8 && R.chance(s, 0.35)) return ranked[0].id;
  return "skip";
}

function tickMeetingBots(s) {
  for (const p of s.ps) {
    if (p.ctl !== "b" || !p.b || !p.alive || p.spec) continue;
    const b = p.b;
    while (b.plan.length && b.plan[0].at <= s.now && s.now - (p.lastChat || 0) >= 1200) {
      const line = b.plan.shift();
      chatLine(s, p, line.text, line.about ? { about: line.about, k: line.k } : undefined);
      botsHear(s, s.meet.chat[s.meet.chat.length - 1]);
    }
    b.plan.sort((x, y) => x.at - y.at);
    if (s.phase === "VOTE" && !p.voted && b.voteAt && s.now >= b.voteAt) applyVote(s, p, botChoose(s, p));
  }
}
// ---------------------------------------------------------------------------
// The six exports, plus the server clock tick and presence system actions.
// ---------------------------------------------------------------------------

export function setup(players) {
  return freshState(players.slice(), 0);
}

const OK = { ok: true };
const no = (error) => ({ ok: false, error });

export function validateAction(state, playerId, a) {
  if (!a || typeof a !== "object" || typeof a.t !== "string") return no("bad action");
  if (a.t.startsWith("_")) return no("not allowed");
  const s = Object.assign({}, state, { now: Math.max(state.now || 0, Number(a._now) || 0) });
  const p = pOf(s, playerId);
  if (!p) return no("join first");
  switch (a.t) {
    case "hello":
      if (typeof a.name !== "string" || a.name.length > 40) return no("bad name");
      if (a.look !== undefined && typeof a.look !== "string") return no("bad look");
      if (!p.hello && !cleanName(a.name)) return no("Pick a name of 2 to 14 letters.");
      return OK;
    case "look":
      if (s.phase !== "LOBBY") return no("not now");
      if (!LOOKS.includes(a.look)) return no("bad look");
      if (s.ps.some((q) => q !== p && q.look === a.look)) return no("Someone already picked that look.");
      return OK;
    case "opts":
      if (s.phase !== "LOBBY") return no("not now");
      if (s.host !== p.id) return no("Only the host can change settings.");
      return OK;
    case "start":
      if (s.phase !== "LOBBY") return no("not now");
      if (s.host !== p.id) return no("Only the host can start.");
      if (!lobbyHumans(s).length) return no("Nobody is here.");
      return OK;
    case "again":
      if (s.phase !== "END") return no("not now");
      if (s.host !== p.id && !s.pub) return no("Only the host can restart.");
      return OK;
    case "p": {
      const e = checkMove(s, p, a);
      return e ? no(e) : OK;
    }
    case "use": {
      if (s.phase !== "PLAY" || p.spec) return no("not now");
      if (!STATIONS[a.id] || STATIONS[a.id].kind === "bell") return no("no such station");
      if (!nearStation(p, a.id)) return no("Get closer.");
      const e = stationOpen(s, p, a.id);
      return e ? no(e) : OK;
    }
    case "done": {
      if (s.phase !== "PLAY" || p.spec) return no("not now");
      if (!p.act || p.act.id !== a.id) return no("Start it first.");
      const st = STATIONS[a.id];
      if (s.now - p.act.at < st.dur * 1000 * T.taskSlack) return no("Too fast.");
      if (!nearStation(p, a.id, RANGE.use + 0.6)) return no("Get closer.");
      const e = stationOpen(s, p, a.id);
      return e ? no(e) : OK;
    }
    case "cancel":
      return OK;
    case "strike": {
      const e = canStrike(s, p, pOf(s, a.who));
      return e ? no(e) : OK;
    }
    case "report":
      if (s.phase !== "PLAY" || !p.alive || p.spec) return no("not now");
      return bodyNear(s, p) ? OK : no("No body here.");
    case "bell":
      if (s.phase !== "PLAY" || !p.alive || p.spec) return no("not now");
      if (!nearStation(p, "bell", RANGE.bell)) return no("Get to the bell in the lounge.");
      if (p.bell <= 0) return no("You already rang the bell this game.");
      if (s.sab) return no("Fix the sabotage first.");
      if (s.now < s.bellAt) return no("The bell is cooling down.");
      return OK;
    case "sab": {
      const e = canSabotage(s, p, a.k);
      return e ? no(e) : OK;
    }
    case "chat": {
      const e = checkChat(s, p, a);
      return e ? no(e) : OK;
    }
    case "vote": {
      const e = checkVote(s, p, a);
      return e ? no(e) : OK;
    }
    default:
      return no("unknown action");
  }
}

export function applyAction(state, playerId, a) {
  // Movement is the hot path (several times a second per player): copy only what changes.
  if (a.t === "p") {
    const s = Object.assign({}, state, { now: Math.max(state.now || 0, Number(a._now) || 0) });
    s.ps = state.ps.slice();
    const i = s.ps.findIndex((q) => q.id === playerId);
    if (i < 0) return state;
    s.ps[i] = Object.assign({}, s.ps[i]);
    applyMove(s, s.ps[i], a);
    return s;
  }
  const s = clone(state);
  s.now = Math.max(s.now || 0, Number(a._now) || 0);
  if (a.t === "_tick") { tick(s); return s; }
  if (a.t === "_join") { join(s, playerId); bump(s); return s; }
  if (a.t === "_leave") { leave(s, playerId); bump(s); return s; }
  const p = pOf(s, playerId);
  if (!p) return state;
  switch (a.t) {
    case "hello":
      if (s.phase === "LOBBY" || !p.hello || p.spec) hello(s, p, a);
      break;
    case "look": p.look = a.look; break;
    case "opts": setOpts(s, a); break;
    case "start": startRound(s); break;
    case "again": toLobby(s); break;
    case "use": p.act = { id: a.id, at: s.now }; break;
    case "done": finishStation(s, p, a.id); break;
    case "cancel": p.act = null; break;
    case "strike": strike(s, p, pOf(s, a.who)); break;
    case "report": startMeeting(s, p.id, "body", bodyNear(s, p).id); break;
    case "bell": p.bell -= 1; startMeeting(s, p.id, "bell", null); break;
    case "sab": sabotage(s, p, a.k); break;
    case "chat": applyChat(s, p, a); break;
    case "vote": applyVote(s, p, a.who); break;
  }
  bump(s);
  return s;
}

/** A browser for this seat connected. Returning players get their body back. */
function join(s, id) {
  const p = pOf(s, id);
  if (p) {
    p.on = true; p.away = 0;
    if (!p.bot && p.ctl === "b") { p.ctl = "h"; p.b = null; if (s.phase === "PLAY") feed(s, `${p.name} is back.`, "join"); }
    return;
  }
  const q = newPlayer(id, false);
  q.on = true;
  if (s.phase !== "LOBBY") { q.spec = true; q.alive = false; }
  s.ps.push(q);
}

/** The last browser for this seat closed. */
function leave(s, id) {
  const p = pOf(s, id);
  if (!p) return;
  p.on = false; p.away = s.now;
  if (s.phase === "LOBBY" || p.spec) {
    s.ps = s.ps.filter((q) => q !== p);
    if (p.hello && !p.spec) feed(s, `${p.name} left.`, "join");
  }
  if (s.host === id) { const next = s.ps.find((q) => !q.bot && q.on && q.hello); s.host = next ? next.id : null; }
  if (s.phase === "LOBBY" && s.pub && !lobbyHumans(s).length) s.fillAt = 0;
}

function tick(s) {
  const dt = Math.min(0.5, Math.max(0, (s.now - (s.lastTick || s.now)) / 1000));
  s.lastTick = s.now;
  const before = s.phase;
  switch (s.phase) {
    case "LOBBY":
      if (s.pub && s.fillAt && s.now >= s.fillAt && lobbyHumans(s).some((p) => p.on)) startRound(s);
      break;
    case "INTRO":
      if (s.now >= s.ends) openPlay(s);
      break;
    case "PLAY":
      for (const p of s.ps) {
        if (!p.bot && !p.on && p.ctl === "h" && !p.spec && s.now - p.away > T.away) {
          p.ctl = "b"; p.b = brainNew();
          if (p.alive) feed(s, `${p.name}'s network dropped. AI is playing for them until they're back.`, "join");
        }
      }
      tickPlay(s);
      if (s.phase === "PLAY") tickBots(s, dt);
      break;
    case "MEET":
      tickMeetingBots(s);
      if (s.now >= s.ends) openVote(s);
      break;
    case "VOTE":
      tickMeetingBots(s);
      if (s.phase === "VOTE" && s.now >= s.ends) closeVote(s);
      break;
    case "RESULT":
      if (s.now >= s.ends) afterResult(s);
      break;
    case "END":
      if (s.pub && s.now >= s.ends) toLobby(s);
      break;
  }
  if (s.phase !== before || s.moved || s.dirty) { bump(s); s.moved = false; s.dirty = false; }
}

export function isGameOver() {
  return { over: false };
}

const SHOW_ALL = new Set(["INTRO", "MEET", "VOTE", "RESULT", "END"]);

export function viewFor(state, playerId) {
  const s = state;
  const me = pOf(s, playerId);
  const base = { v: s.ver, phase: s.phase, now: s.now, ends: s.ends, fillAt: s.fillAt, pub: s.pub, host: s.host, opts: s.opts, round: s.round, bar: s.phase === "LOBBY" ? 0 : Math.round(taskBar(s) * 1000) / 1000, feed: s.feed };
  if (!me) return Object.assign(base, { me: null, ps: s.ps.filter((p) => p.hello).map((p) => ({ id: p.id, name: p.name, look: p.look, bot: p.bot })) });
  const ghost = !me.alive || me.spec;
  const end = s.phase === "END";
  const ps = [];
  for (const p of s.ps) {
    if (!p.hello) continue;
    const o = { id: p.id, name: p.name, look: p.look, bot: p.bot, on: p.on };
    if (s.phase !== "LOBBY") {
      o.spec = p.spec || undefined;
      o.alive = ghost || end || p.known || p.id === me.id ? p.alive : true;
      if (!o.alive && p.ejected) o.ej = 1;
      const show = p.id === me.id || (p.alive ? (ghost || SHOW_ALL.has(s.phase) || sees(s, me, p)) : ghost && !p.spec);
      if (show && !p.spec) { o.x = p.x; o.z = p.z; o.f = p.f; o.mv = p.mv; }
      if (end || (isSab(me) && isSab(p))) o.role = p.role;
      if (s.phase === "VOTE" || s.phase === "RESULT") o.voted = p.voted ? 1 : 0;
      if (s.meet && s.meet.seats) { const k = s.meet.seats.indexOf(p.id); if (k >= 0) o.seat = k; }
    }
    ps.push(o);
  }
  const view = Object.assign(base, {
    me: {
      id: me.id, name: me.name, look: me.look, hello: me.hello, role: s.phase === "LOBBY" ? null : me.role, alive: me.alive, spec: me.spec, ghost,
      x: me.x, z: me.z, f: me.f, tp: me.tp, tasks: me.tasks, act: me.act, bell: me.bell,
      cd: isSab(me) ? me.cd : 0, ej: me.ejected || undefined,
    },
    ps,
    vis: s.phase === "PLAY" ? visionOf(s, me) : 0,
    bellAt: s.bellAt,
    bodies: s.phase === "PLAY" ? s.bodies.filter((b) => ghost || seesPoint(s, me, b.x, b.z)).map((b) => ({ id: b.id, x: b.x, z: b.z })) : [],
    sab: s.sab ? { k: s.sab.k, ends: s.sab.ends, fixed: s.sab.fixed } : null,
  });
  if (isSab(me)) view.sabAt = s.sabAt;
  if (s.phase === "PLAY" && s.flash && s.flash.length) {
    const fl = s.flash.filter((f) => s.now - f.at < 3000 && (ghost || f.to.includes(me.id) || f.id === me.id)).map((f) => ({ i: f.i, id: f.id }));
    if (fl.length) view.flash = fl;
  }
  if (s.meet) {
    view.meet = {
      by: s.meet.by, kind: s.meet.kind, body: s.meet.body, room: s.meet.room,
      chat: s.meet.chat.filter((c) => !c.g || ghost).map((c) => ({ i: c.i, w: c.w, t: c.t, g: c.g || undefined })),
      myVote: me.voted,
    };
  }
  if (s.res) view.res = { out: s.res.out, role: s.opts.reveal || end ? s.res.role : null, tally: s.res.tally, skips: s.res.skips, tie: s.res.tie };
  if (s.end) view.end = { win: s.end.win, why: s.end.why, stats: s.stats };
  return view;
}
